---
- name: Simple Rulebook
  hosts: localhost
  sources:
    - ansible.eda.range:
        limit: 1
  rules:
    - name: Print a message when event occurs
      condition: event.i == 0
      action:
        run_playbook:
          name: print_message.yml
