---
- name: Simple Rulebook
  hosts: localhost
  sources:
    - ansible.eda.range:
        limit: 1
    # - ansible.eda.webhook:
    #     host: 0.0.0.0
    #     port: 5000
  rules:
    - name: Print a message when event occurs
      condition: event.i == 0
      action:
        run_playbook:
          name: sample-play.yml
    # - name: Print a message when event occurs
    #   condition: event.payload.message == "Ansible super"
    #   action:
    #     debug:
    #       msg: 'hey there from ansible EDA'
