---
- name: job template trigger rule
  hosts: localhost
  sources:
    - ansible.eda.range:
        limit: 2
  rules:
    - name: Print a message when event occurs
      condition: event.i == 2
      action:
          run_job_template:
            name: "sample-hello"
            organization: "Default"